In [70]:
import pandas as pd

## 1. Create

### 1.1 Create

In [71]:
df = pd.read_csv("Datasets/telco_churn.csv")

1.2 Create from Dictionary

In [72]:
tempdict = {'col1':[1,2,3], 'col2':[1,2,3], 'col3':[1,2,3]}

In [73]:
dictdf = pd.DataFrame.from_dict(tempdict)

## 2. Read

2.1 Show Top 5 and Bottom 5 Rows

In [74]:
df.head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False
2,NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False

In [75]:
dictdf.head()

   col1  col2  col3
0     1     1     1
1     2     2     2
2     3     3     3

In [76]:
df.tail()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
3328,AZ,192,415,No,Yes,36,156.2,77.0,26.55,215.5,126.0,18.32,279.1,83.0,12.56,9.9,6,2.67,2.0,False
3329,WV,68,415,No,No,0,231.1,57.0,39.29,153.4,55.0,13.04,191.3,123.0,8.61,9.6,4,2.59,3.0,False
3330,RI,28,510,No,No,0,180.8,109.0,30.74,288.8,58.0,24.55,191.9,91.0,8.64,14.1,6,3.81,2.0,False
3331,CT,184,510,Yes,No,0,213.8,105.0,36.35,159.6,84.0,13.57,139.2,137.0,6.26,5.0,10,1.35,2.0,False
3332,TN,74,415,No,Yes,25,234.4,113.0,39.85,265.9,82.0,22.60,241.4,77.0,10.86,13.7,4,3.70,0.0,False

In [77]:
df.tail()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
3328,AZ,192,415,No,Yes,36,156.2,77.0,26.55,215.5,126.0,18.32,279.1,83.0,12.56,9.9,6,2.67,2.0,False
3329,WV,68,415,No,No,0,231.1,57.0,39.29,153.4,55.0,13.04,191.3,123.0,8.61,9.6,4,2.59,3.0,False
3330,RI,28,510,No,No,0,180.8,109.0,30.74,288.8,58.0,24.55,191.9,91.0,8.64,14.1,6,3.81,2.0,False
3331,CT,184,510,Yes,No,0,213.8,105.0,36.35,159.6,84.0,13.57,139.2,137.0,6.26,5.0,10,1.35,2.0,False
3332,TN,74,415,No,Yes,25,234.4,113.0,39.85,265.9,82.0,22.60,241.4,77.0,10.86,13.7,4,3.70,0.0,False

### 2.2 Show Columns and Data Type

In [78]:
df.columns

Index(['State', 'Account length', 'Area code', 'International plan',
       'Voice mail plan', 'Number vmail messages', 'Total day minutes',
       'Total day calls', 'Total day charge', 'Total eve minutes',
       'Total eve calls', 'Total eve charge', 'Total night minutes',
       'Total night calls', 'Total night charge', 'Total intl minutes',
       'Total intl calls', 'Total intl charge', 'Customer service calls',
       'Churn'],
      dtype='object')

In [79]:
df.dtypes

State                      object
Account length              int64
Area code                   int64
International plan         object
Voice mail plan            object
Number vmail messages       int64
Total day minutes         float64
Total day calls           float64
Total day charge          float64
Total eve minutes         float64
Total eve calls           float64
Total eve charge          float64
Total night minutes       float64
Total night calls         float64
Total night charge        float64
Total intl minutes        float64
Total intl calls            int64
Total intl charge         float64
Customer service calls    float64
Churn                      object
dtype: object

### 2.3 Summary Statistics

In [80]:
df.describe()

,Account length,Area code,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls
count,3333.000000,3333.000000,3333.000000,3323.000000,3323.000000,3315.000000,3324.000000,3325.000000,3333.000000,3333.000000,3332.000000,3333.000000,3333.000000,3333.000000,3328.000000,3328.000000
mean,101.064806,437.182418,8.099010,179.787150,100.456214,30.557831,201.033935,100.110677,17.083540,200.872037,100.115246,9.039325,10.237294,4.479448,2.764588,1.563101
std,39.822106,42.371290,13.688365,54.419625,20.057356,9.255987,50.676652,19.932115,4.310668,50.573847,19.566710,2.275873,2.791840,2.461214,0.754086,1.315870
min,1.000000,408.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,23.200000,33.000000,1.040000,0.000000,0.000000,0.000000,0.000000
25%,74.000000,408.000000,0.000000,143.700000,87.000000,24.420000,166.600000,87.000000,14.160000,167.000000,87.000000,7.520000,8.500000,3.000000,2.300000,1.000000
50%,101.000000,415.000000,0.000000,179.400000,101.000000,30.500000,201.400000,100.000000,17.120000,201.200000,100.000000,9.050000,10.300000,4.000000,2.780000,1.000000
75%,127.000000,510.000000,20.000000,216.500000,114.000000,36.780000,235.325000,114.000000,20.000000,235.300000,113.000000,10.590000,12.100000,6.000000,3.270000,2.000000
max,243.000000,510.000000,51.000000,350.800000,165.000000,59.640000,363.700000,170.000000,30.910000,395.000000,175.000000,17.770000,20.000000,20.000000,5.400000,9.000000

In [81]:
df.describe(include='object')

       State International plan Voice mail plan  Churn
count   3333               3333            3333   3325
unique    51                  2               2      2
top       WV                 No              No  False
freq     106               3010            2411   2842

### 2.4 Filtering Columns

In [82]:
df.State

0       KS
1       OH
2       NJ
3       OH
4       OK
        ..
3328    AZ
3329    WV
3330    RI
3331    CT
3332    TN
Name: State, Length: 3333, dtype: object

In [83]:
df[['State', 'International plan']]

     State International plan
0       KS                 No
1       OH                 No
2       NJ                 No
3       OH                Yes
4       OK                Yes
...    ...                ...
3328    AZ                 No
3329    WV                 No
3330    RI                 No
3331    CT                Yes
3332    TN                 No

[3333 rows x 2 columns]

In [84]:
df.State.unique()

array(['KS', 'OH', 'NJ', 'OK', 'AL', 'MA', 'MO', 'LA', 'WV', 'IN', 'RI',
       'IA', 'MT', 'NY', 'ID', 'VT', 'VA', 'TX', 'FL', 'CO', 'AZ', 'SC',
       'NE', 'WY', 'HI', 'IL', 'NH', 'GA', 'AK', 'MD', 'AR', 'WI', 'OR',
       'MI', 'DE', 'UT', 'CA', 'MN', 'SD', 'NC', 'WA', 'NM', 'NV', 'DC',
       'KY', 'ME', 'MS', 'TN', 'PA', 'CT', 'ND'], dtype=object)

### 2.5 Filtering on Rows

In [85]:
df[ df['Voice mail plan'] == 'Yes']

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False
6,MA,121,510,No,Yes,24,218.2,88.0,37.09,348.5,108.0,29.62,212.6,118.0,9.57,7.5,7,2.03,3.0,NaN
9,WV,141,415,Yes,Yes,37,258.6,84.0,43.96,222.0,111.0,18.87,326.4,97.0,14.69,11.2,5,3.02,0.0,False
16,ID,85,408,No,Yes,27,NaN,NaN,NaN,280.9,90.0,23.88,89.3,NaN,4.02,13.8,4,3.73,1.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3306,AL,106,408,No,Yes,29,83.6,131.0,14.21,203.9,131.0,17.33,229.5,73.0,10.33,8.1,3,2.19,1.0,False
3315,ME,149,415,No,Yes,18,148.5,106.0,25.25,114.5,106.0,9.73,178.3,98.0,8.02,6.5,4,1.76,0.0,False
3316,MS,103,510,No,Yes,29,164.1,111.0,27.90,219.1,96.0,18.62,220.3,108.0,9.91,12.3,9,3.32,0.0,False
3328,AZ,192,415,No,Yes,36,156.2,77.0,26.55,215.5,126.0,18.32,279.1,83.0,12.56,9.9,6,2.67,2.0,False
3332,TN,74,415,No,Yes,25,234.4,113.0,39.85,265.9,82.0,22.60,241.4,77.0,10.86,13.7,4,3.70,0.0,False

In [86]:
df[ (df['Voice mail plan'] == 'No') & (df['Total eve minutes'] < 99)]

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False
22,AZ,130,415,No,No,0,183.0,112.0,31.11,72.9,99.0,6.20,181.8,78.0,8.18,9.5,19,2.57,0.0,NaN
77,NY,144,408,No,No,0,61.6,117.0,10.47,77.1,85.0,6.55,173.0,99.0,7.79,8.2,7,2.21,4.0,True
95,AK,104,408,No,No,0,278.4,106.0,47.33,81.0,113.0,6.89,163.2,137.0,7.34,9.8,5,2.65,1.0,False
186,NY,106,408,No,No,0,158.7,74.0,26.98,64.3,139.0,5.47,198.5,103.0,8.93,10.2,4,2.75,1.0,False
191,TX,130,415,No,No,0,176.9,109.0,30.07,90.7,104.0,7.71,238.0,69.0,10.71,9.5,2,2.57,1.0,False
206,IN,122,415,No,No,0,243.8,98.0,41.45,83.9,72.0,7.13,179.8,84.0,8.09,13.7,8,3.70,2.0,False
240,NJ,138,510,No,No,0,220.2,89.0,37.43,88.3,125.0,7.51,195.3,79.0,8.79,12.9,5,3.48,0.0,False
355,ME,31,415,No,No,0,166.1,105.0,28.24,79.3,93.0,6.74,213.7,98.0,9.62,12.7,2,3.43,1.0,False
534,LA,67,510,No,No,0,310.4,97.0,52.77,66.5,123.0,5.65,246.5,99.0,11.09,9.2,10,2.48,4.0,False
563,ID,99,415,No,No,0,145.6,106.0,24.75,98.3,106.0,8.36,230.8,83.0,10.39,10.9,5,2.94,1.0,False
587,NH,114,415,No,No,0,169.6,85.0,28.83,58.9,86.0,5.01,179.3,124.0,8.07,7.4,8,2.00,1.0,False
592,OK,92,510,No,No,0,176.3,85.0,29.97,93.4,125.0,7.94,207.2,107.0,9.32,9.6,1,2.59,2.0,False
712,MO,106,415,No,No,0,114.4,104.0,19.45,78.3,101.0,6.66,232.7,78.0,10.47,0.0,0,0.00,2.0,False
821,MN,80,415,No,No,0,105.8,110.0,17.99,43.9,88.0,3.73,189.6,87.0,8.53,13.1,5,3.54,0.0,False
830,CO,121,408,Yes,No,0,167.7,94.0,28.51,93.7,121.0,7.96,241.3,115.0,10.86,13.4,1,3.62,3.0,True
850,WA,166,408,No,No,0,274.3,110.0,46.63,52.9,109.0,4.50,246.1,119.0,11.07,10.9,5,2.94,0.0,False
889,MN,103,415,No,No,0,198.5,112.0,33.75,42.5,90.0,3.61,179.2,124.0,8.06,12.4,5,3.35,0.0,False
893,MO,167,415,Yes,No,0,244.8,91.0,41.62,60.8,105.0,5.17,176.7,110.0,7.95,10.7,3,2.89,2.0,False
905,WV,161,415,No,No,0,191.9,113.0,32.62,70.9,87.0,6.03,204.8,107.0,9.22,13.4,4,3.62,4.0,True
925,NC,43,415,No,No,0,84.2,134.0,14.31,80.8,103.0,6.87,196.1,79.0,8.82,10.8,2,2.92,1.0,False
1014,OH,102,415,No,No,0,114.8,125.0,19.52,81.9,126.0,6.96,304.3,101.0,13.69,12.0,4,3.24,0.0,False
1054,AK,50,408,No,No,0,183.6,107.0,31.21,58.6,118.0,4.98,202.6,99.0,9.12,8.7,3,2.35,1.0,False
1056,KS,67,408,No,No,0,201.4,101.0,34.24,97.6,122.0,8.30,202.5,119.0,9.11,7.0,3,1.89,0.0,False
1060,OH,124,510,No,No,0,193.0,97.0,32.81,89.8,99.0,7.63,172.8,104.0,7.78,15.3,3,4.13,1.0,False
1108,WY,151,510,No,No,0,235.9,104.0,40.10,80.6,91.0,6.85,212.8,116.0,9.58,5.8,2,1.57,3.0,False
1148,NY,122,415,No,No,0,173.6,110.0,29.51,91.7,84.0,7.79,211.7,103.0,9.53,9.7,7,2.62,3.0,False
1190,NE,149,415,No,No,0,156.0,56.0,26.52,56.0,116.0,4.76,163.3,104.0,7.35,8.9,8,2.40,0.0,False
1233,IL,48,510,No,No,0,128.2,71.0,21.79,48.1,78.0,4.09,116.3,80.0,5.23,8.9,3,2.40,0.0,False
1315,NH,124,415,No,No,0,254.3,113.0,43.23,78.9,104.0,6.71,153.2,69.0,6.89,11.8,2,3.19,2.0,False
1335,WY,71,415,No,No,0,243.7,124.0,41.43,60.0,90.0,5.10,189.0,129.0,8.50,11.3,2,3.05,0.0,False
1343,MD,73,510,No,No,0,254.7,80.0,43.30,90.2,79.0,7.67,153.4,60.0,6.90,10.6,8,2.86,0.0,False
1362,WV,63,510,No,No,0,132.9,122.0,22.59,67.0,62.0,5.70,160.4,121.0,7.22,9.9,2,2.67,3.0,False
1403,KY,126,510,No,No,0,175.4,120.0,29.82,98.3,71.0,8.36,201.9,93.0,9.09,10.6,1,2.86,0.0,False
1405,MT,125,510,No,No,0,143.2,80.0,24.34,88.1,94.0,7.49,233.2,135.0,10.49,8.8,7,2.38,4.0,True
1475,AZ,70,415,No,No,0,104.7,112.0,17.80,82.2,104.0,6.99,169.4,110.0,7.62,15.8,7,4.27,3.0,False
1538,WV,113,415,No,No,0,61.2,111.0,10.40,92.3,88.0,7.85,197.4,114.0,8.88,13.7,3,3.70,5.0,True
1789,GA,133,510,No,No,0,227.4,90.0,38.66,73.2,135.0,6.22,114.3,99.0,5.14,4.7,7,1.27,0.0,False
1839,AL,70,415,No,No,0,230.3,110.0,39.15,77.9,87.0,6.62,247.1,105.0,11.12,13.2,4,3.56,1.0,False
1927,OK,110,510,No,No,0,188.0,127.0,31.96,90.5,118.0,7.69,150.3,64.0,6.76,15.3,3,4.13,3.0,False
1960,TX,38,510,No,No,0,149.0,92.0,25.33,49.2,78.0,4.18,163.3,93.0,7.35,13.9,11,3.75,0.0,False
2081,AL,82,408,No,No,0,154.0,107.0,26.18,94.4,114.0,8.02,287.6,95.0,12.94,10.1,7,2.73,1.0,False
2174,ND,160,510,No,No,0,121.8,97.0,20.71,89.3,97.0,7.59,150.7,92.0,6.78,10.3,5,2.78,1.0,False
2305,NE,123,415,No,No,0,150.0,98.0,25.50,89.8,95.0,7.63,326.0,91.0,14.67,11.1,3,3.00,3.0,False
2316,CT,135,415,Yes,No,0,186.0,107.0,31.62,66.0,94.0,5.61,213.1,105.0,9.59,12.9,4,3.48,1.0,False
2328,KY,122,415,No,No,0,168.3,96.0,28.61,87.6,91.0,7.45,247.2,87.0,11.12,8.4,6,2.27,1.0,False
2361,MA,66,415,No,No,0,116.4,98.0,19.79,95.6,74.0,8.13,181.5,94.0,8.17,10.5,3,2.84,3.0,False
2448,VA,138,415,No,No,0,251.0,119.0,42.67,91.2,96.0,7.75,142.2,87.0,6.40,13.8,3,3.73,3.0,False
2562,KS,110,510,No,No,0,208.0,69.0,35.36,95.1,94.0,8.08,178.5,129.0,8.03,8.0,11,2.16,1.0,False
2720,MI,158,415,No,No,0,195.9,103.0,33.30,89.1,95.0,7.57,302.2,82.0,13.60,10.3,3,2.78,1.0,False
2859,WV,87,415,No,No,0,58.0,125.0,9.86,67.5,116.0,5.74,185.9,136.0,8.37,11.5,3,3.11,0.0,False
2932,UT,97,415,No,No,0,209.2,134.0,35.56,0.0,0.0,0.00,175.4,94.0,7.89,11.8,6,3.19,1.0,False
2940,HI,24,415,No,No,0,156.2,104.0,26.55,90.0,101.0,7.65,205.1,116.0,9.23,7.3,5,1.97,1.0,False
2965,WI,103,415,No,No,0,180.2,134.0,30.63,97.7,85.0,8.30,181.7,134.0,8.18,8.4,3,2.27,1.0,False
3200,CT,100,510,Yes,No,0,107.2,98.0,18.22,86.8,122.0,7.38,156.2,117.0,7.03,9.7,4,2.62,1.0,False
3233,OK,112,415,No,No,0,166.0,79.0,28.22,74.6,100.0,6.34,247.9,74.0,11.16,6.3,7,1.70,0.0,False
3292,IN,114,408,No,No,0,203.8,85.0,34.65,87.8,110.0,7.46,166.2,122.0,7.48,11.7,4,3.16,1.0,False
3310,NY,94,415,No,No,0,190.4,91.0,32.37,92.0,107.0,7.82,224.8,108.0,10.12,13.6,17,3.67,2.0,False
3321,VT,60,415,No,No,0,193.9,118.0,32.96,85.0,110.0,7.23,210.1,134.0,9.45,13.2,8,3.56,3.0,False

In [87]:
filter_data = df[ (df['Voice mail plan'] == 'No') & (df['Total eve minutes'] < 99)]

### 2.6 Indexing with iloc

In [88]:
df.iloc[14]

State                        IA
Account length               62
Area code                   415
International plan           No
Voice mail plan              No
Number vmail messages         0
Total day minutes           NaN
Total day calls             NaN
Total day charge            NaN
Total eve minutes         307.2
Total eve calls            76.0
Total eve charge          26.11
Total night minutes       203.0
Total night calls          99.0
Total night charge         9.14
Total intl minutes         13.1
Total intl calls              6
Total intl charge          3.54
Customer service calls      4.0
Churn                     False
Name: 14, dtype: object

In [89]:
df.iloc[14,0]

'IA'

In [90]:
df.iloc[14,-1]

False

In [91]:
df.iloc[22:33]

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
22,AZ,130,415,No,No,0,183.0,112.0,31.11,72.9,99.0,6.20,181.8,78.0,8.18,9.5,19,2.57,0.0,NaN
23,SC,111,415,No,No,0,110.4,103.0,18.77,137.3,102.0,11.67,189.6,105.0,8.53,7.7,6,2.08,2.0,False
24,VA,132,510,No,No,0,81.1,86.0,13.79,245.2,72.0,20.84,237.0,115.0,10.67,10.3,2,2.78,0.0,False
25,NE,174,415,No,No,0,124.3,76.0,21.13,277.1,112.0,23.55,250.7,115.0,11.28,15.5,5,4.19,3.0,False
26,WY,57,408,No,Yes,39,213.0,115.0,36.21,191.1,112.0,16.24,182.7,115.0,8.22,9.5,3,2.57,0.0,False
27,MT,54,408,No,No,0,134.3,73.0,22.83,155.5,100.0,13.22,102.1,68.0,4.59,14.7,4,3.97,3.0,False
28,MO,20,415,No,No,0,190.0,109.0,32.30,258.2,84.0,21.95,181.5,102.0,8.17,6.3,6,1.70,0.0,False
29,HI,49,510,No,No,0,119.3,117.0,20.28,215.1,109.0,18.28,178.7,90.0,8.04,11.1,1,3.00,1.0,NaN
30,IL,142,415,No,No,0,84.8,95.0,14.42,136.7,63.0,11.62,250.5,148.0,11.27,14.2,6,3.83,2.0,False
31,NH,75,510,No,No,0,226.1,105.0,NaN,NaN,NaN,17.13,246.2,98.0,11.08,10.3,5,2.78,1.0,False
32,LA,172,408,No,No,0,212.0,121.0,NaN,NaN,NaN,2.65,293.3,78.0,13.20,12.6,10,3.40,3.0,False

### 2.7 Indexing with loc

In [92]:
state = df.copy()
state.setIndex("State",inplace=True)

AttributeError: 'DataFrame' object has no attribute 'setIndex'

In [ ]:
state.head()

## 3 Update

### 3.1 Dropping Rows

In [ ]:
df.isnull().sum()

In [ ]:
df.dropna(inplace=True)

In [ ]:
df.isnull().sum()

### 3.2 Dropping Columns

### 3.2 Dropping Columns

In [ ]:
df.drop('Churn', axis=1)

### 3.3 Creating calculated columns

In [ ]:
df['New Column'] = df["Area code"] + df["Account length"]

In [ ]:
df.head()

 ### 3.4 Updating entire columns

In [ ]:
df['New Column'] = 100

In [ ]:
df.head()

### 3.5 Updating a single value

In [ ]:
df.iloc[0,1] = 888

In [ ]:
df.head()

### 3.6 Condition based Updating using Apply

In [ ]:
df['Churn Binary'] = df['Churn'].apply(lambda x: 1 if x == True else 0)

In [ ]:
df.head()

### 4. Delete/Output

### 4.1 Output to CSV

In [94]:
df.to_csv('result.csv')

### 4.2 Output to JSON

In [95]:
df.to_json('result.json')

In [97]:
##df.to_json() to long to print

### 4.3 Output to HTML

In [99]:
df.to_html('result.html')

### 4.4 Delete a DataFrame

In [ ]:
## del df